youstaproject/api/urls.py
from django.urls import path
from api import views
from rest_framework.routers import DefaultRouter
from rest_framework.authtoken.views import ObtainAuthToken

router=DefaultRouter()
router.register("cloths",views.ClothsView,basename="cloths")
router.register("carts",views.CartsView,basename="carts")
router.register("orders",views.OrdersView,basename="orders")

urlpatterns=[

path("register/",views.UserCreationView.as_view()),
path("token/",ObtainAuthToken.as_view())

]+router.urls

youstaproject/yousta/urls.py
from django.urls import path

from yousta.views import SignUpView,SignInView,CategoryCreateView,remove_category\
,ClothCreateView,ClothListView,ClothUpdateView,remove_clothview,ClothVarientCreateView,\
    ClothDetailView,ClothVarientUpdateView,remove_varient,OfferCreateView,offer_delete_view,\
    sign_out_view
    



urlpatterns=[

    path("register/",SignUpView.as_view(),name="signup"),
    path("categories/add",CategoryCreateView.as_view(),name="add-category"),
    path("",SignInView.as_view(),name="signin"),
    path("categories/<int:pk>/remove",remove_category,name="remove-category"),
    path("cloths/add",ClothCreateView.as_view(),name="cloth-add"),
    path("cloths/all",ClothListView.as_view(),name="cloth-list"),
    path("cloths/<int:pk>/change",ClothUpdateView.as_view(),name="cloth-change"),
    path("cloths/<int:pk>/remove",remove_clothview,name="cloth-remove"),
    path("cloths/<int:pk>/varients/add",ClothVarientCreateView.as_view(),name="add-varient"),
    path("cloths/<int:pk>/",ClothDetailView.as_view(),name="cloth-detail"),
    path("varients/<int:pk>/change/",ClothVarientUpdateView.as_view(),name="update-varient"),
    path("varients/<int:pk>/remove",remove_varient,name="remove-varient"),
    path("varients/<int:pk>/offers/add",OfferCreateView.as_view(),name="offers-add"),
    path("offers/<int:pk>/remove",offer_delete_view,name="delete-offer"),
    path("logout/",sign_out_view,name="signout")



]

youstaproject/youstaproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
   
    path("api/",include("api.urls")),
     path("",include("yousta.urls")),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

youstaproject/yousta/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):

    phone=models.CharField(max_length=100,unique=True)
    address=models.CharField(max_length=200)


class Category(models.Model):

    name=models.CharField(max_length=200,unique=True)
    is_active=models.BooleanField(default=True)

    # def __str__(self):
    #     return self.name
    
class Cloths(models.Model):
    name=models.CharField(max_length=200)#ucb shirt
    options=(
        ("linen","linen"),
        ("cotton","cotton"),
        ("satin","satin"),
        ("nylon","nylon"),
        ("polyster","polyster"),
        ("silk","silk")
    )
    material=models.CharField(max_length=200,choices=options,default="cotton")
    image=models.ImageField(upload_to="images")
    brand=models.CharField(max_length=200)
    category=models.ForeignKey(Category,null=True,on_delete=models.SET_NULL)

    @property
    def varients(self):
        qs=self.clothvarients_set.all()
        return qs


    def __str__(self):
        return self.name

class ClothVarients(models.Model):
    price=models.PositiveIntegerField()
    color=models.CharField(max_length=100)
    options=(
        ("S","S"),
        ("M","M"),
        ("L","L"),
        ("XL","XL"),
        ("XXl","XXL")
    )

    size=models.CharField(max_length=200,choices=options,default="M")
    cloth=models.ForeignKey(Cloths,on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.cloth.name


class Offers(models.Model):
    clothvarient=models.ForeignKey(ClothVarients,on_delete=models.CASCADE)
    price=models.PositiveIntegerField()
    start_date=models.DateTimeField()
    due_date=models.DateTimeField()


class Carts(models.Model):
    clothvarient=models.ForeignKey(ClothVarients,on_delete=models.DO_NOTHING)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    options=(
        ("in-cart","in-cart"),
        ("order-placed","order-placed"),
        ("cancelled","cancelled")
    )

    status=models.CharField(max_length=200,choices=options,default="in-cart")
    date=models.DateTimeField(auto_now_add=True)


class Orders(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    clothvarient=models.ForeignKey(ClothVarients,on_delete=models.CASCADE)
    options=(
      
        ("order-placed","order-placed"),
        ("cancelled","cancelled"),
        ("dispatced","dispatched"),
        ("in-transit","in-transit"),
        ("delivered","delivered")
    )
    status=models.CharField(max_length=200,choices=options,default="order-placed")
    orderd_date=models.DateTimeField(auto_now_add=True)
    expected_date=models.DateField(null=True)
    address=models.CharField(max_length=200)

from django.core.validators import MinValueValidator,MaxValueValidator

class Reviews(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    cloth=models.ForeignKey(Cloths,null=True,on_delete=models.SET_NULL)
    rating=models.PositiveIntegerField(validators=[MinValueValidator(1),MaxValueValidator(5)])
    comment=models.CharField(max_length=300)



    


    

youstaproject/yousta/forms.py
from django import forms


from yousta.models import User,Category,Cloths,ClothVarients,Offers
from django.contrib.auth.forms import UserCreationForm

class RegistrationForm(UserCreationForm):

    class Meta:
        model=User
        fields=["username","email","password1","password2","phone","address"]


class LoginForm(forms.Form):

    username=forms.CharField()
    password=forms.CharField(widget=forms.PasswordInput)

class CategoryCreateForm(forms.ModelForm):

    class Meta:
        model=Category
        fields=["name"]


class ClothAddForm(forms.ModelForm):

    class Meta:
        model=Cloths
        fields="__all__"

class ClothVarientForm(forms.ModelForm):

    class Meta:
        model=ClothVarients
        exclude=("cloth",)
        
        # fields=["price","size","color"]



class OfferForm(forms.ModelForm):

    class Meta:
        model=Offers
        exclude=("clothvarient",)
        widgets={
        "start_date":forms.DateInput(attrs={"type":"date"}),
        "due_date":forms.DateInput(attrs={"type":"date"}),

        }

youstaproject/yousta/views.py
from django.db import models
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render,redirect
from django.views.generic import CreateView,FormView,ListView,UpdateView,DetailView
from django.urls import reverse_lazy,reverse
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from django.utils.decorators import method_decorator

from yousta.forms import RegistrationForm,LoginForm,CategoryCreateForm,ClothAddForm,ClothVarientForm,OfferForm
from yousta.models import User,Category,Cloths,ClothVarients,Offers



def signin_required(fn):

    def wrapper(request,*args,**kwargs):
        if not  request.user.is_authenticated:
            messages.error(request,"invalid session!!")
            return redirect("signin")
        else:
            return fn(request,*args,**kwargs)
    return wrapper

def is_admin(fn):

    def wrapper(request,*args,**kwargs):
        if  not request.user.is_superuser:
            messages.error(request,"permission denied for current user ! !")
            return redirect("signin")
        else:
            return fn(request,*args,**kwargs)
    return wrapper


decs=[signin_required,is_admin]




class SignUpView(CreateView):

    template_name="yousta/register.html"
    form_class=RegistrationForm
    model=User
    success_url=reverse_lazy("signin")

    def form_valid(self,form):
        messages.success(self.request,"account created")
        return super().form_valid(form)
    def form_invalid(self, form):
        messages.error(self.request,"failed to create account")
        return super().form_invalid(form)

    
class SignInView(FormView):
    template_name="yousta/login.html"
    form_class=LoginForm

    def post(self,request,*args,**kwargs):
        form=LoginForm(request.POST)

        if form.is_valid():
            uname=form.cleaned_data.get("username")
            pwd=form.cleaned_data.get("password")
            usr=authenticate(request,username=uname,password=pwd)
            if usr:
                login(request,usr)
                messages.success(request,"login successfully")
                return redirect("signin")
            else:
                messages.error(request,"invalid creadential")
                return render(request,self.template_name,{"form":form})


@method_decorator(decs,name="dispatch")
class CategoryCreateView(CreateView,ListView):

    template_name="yousta/category_add.html"
    form_class=CategoryCreateForm
    model=Category
    context_object_name="categories"
    success_url=reverse_lazy("add-category")
    def form_valid(self, form):
        messages.success(self.request,"category added successfully")
        return super().form_valid(form)
    
    def form_invalid(self, form):
        messages.error(self.request,"category adding failed")
        return super().form_invalid(form)
    def get_queryset(self):
        return Category.objects.filter(is_active=True)


@signin_required
@is_admin
def remove_category(request,*args,**kwargs):
    id=kwargs.get("pk")
    Category.objects.filter(id=id).update(is_active=False)
    messages.success(request,"category removed")
    return redirect("add-category")


@method_decorator(decs,name="dispatch")
class ClothCreateView(CreateView):

    template_name="yousta/cloth_add.html"
    model=Cloths
    form_class=ClothAddForm
    success_url=reverse_lazy("cloth-add")

    def form_valid(self,form):
        messages.success(self.request,"cloth hasbeen added")
        return super().form_valid(form)
    def form_invalid(self, form):
        messages.error(self.request,"cloth adding failed ")
        return super().form_invalid(form)

@method_decorator(decs,name="dispatch")   
class ClothListView(ListView):
    template_name="yousta/cloth_list.html"
    model=Cloths
    context_object_name="cloths"

@method_decorator(decs,name="dispatch")
class ClothUpdateView(UpdateView):
    template_name="yousta/cloth_edit.html"
    model=Cloths
    form_class=ClothAddForm
    success_url=reverse_lazy("cloth-list")
    def form_valid(self, form):
        messages.success(self.request,"cloth updated successfully")
        return super().form_valid(form)
    
    def form_invalid(self, form):
        messages.error(self.request,"cloth updating failed")
        return super().form_invalid(form)

@signin_required
@is_admin
def remove_clothview(request,*args,**kwargs):
    id=kwargs.get("pk")
    Cloths.objects.filter(id=id).delete()
    return redirect("cloth-list")

# localhost:8000/clothvarient/1/add
# localhost:8000/cloths/1/varients/add

@method_decorator(decs,name="dispatch")
class ClothVarientCreateView(CreateView):
    template_name="yousta/clothvarient_add.html"
    form_class=ClothVarientForm
    model=ClothVarients
    success_url=reverse_lazy("cloth-list")

    def form_valid(self, form):
        id=self.kwargs.get("pk")
        obj=Cloths.objects.get(id=id)
        form.instance.cloth=obj
        messages.success(self.request,"varient has been added")
    
        return super().form_valid(form)
    
@method_decorator(decs,name="dispatch")
class ClothDetailView(DetailView):
    template_name="yousta/cloth_detail.html"
    model=Cloths
    context_object_name="cloth"


@method_decorator(decs,name="dispatch")
class ClothVarientUpdateView(UpdateView):
    template_name="yousta/varient_edit.html"
    form_class=ClothVarientForm
    model=ClothVarients
    success_url=reverse_lazy("cloth-list")
    def form_valid(self, form):
        messages.success(self.request,"cloth varient successfully")
        return super().form_valid(form)
    
    def form_invalid(self, form):
        messages.error(self.request,"cloth varient updating failed")
        return super().form_invalid(form)
    
    def get_success_url(self):
        id=self.kwargs.get("pk")
        cloth_varient_object=ClothVarients.objects.get(id=id)
        cloth_id=cloth_varient_object.cloth.id
        return reverse("cloth-detail",kwargs={"pk":cloth_id})

@signin_required
@is_admin
def remove_varient(request,*args,**kwargs):
    id=kwargs.get("pk")
    ClothVarients.objects.filter(id=id).delete()
    return redirect("cloth-list")


# localhost:8000/varients/<int:pk>/offers/add
@method_decorator(decs,name="dispatch")
class OfferCreateView(CreateView):
    template_name="yousta/offer_add.html"
    form_class=OfferForm
    model=Offers
    success_url=reverse_lazy("cloth-list")
    
    def form_valid(self, form):
        id=self.kwargs.get("pk")
        obj=ClothVarients.objects.get(id=id)
        form.instance.clothvarient=obj

        messages.success(self.request,"offer has been added successfully")
        return super().form_valid(form)
    
    def form_invalid(self, form):
        messages.error(self.request,"failed")
        return super().form_invalid(form)
    
    def get_success_url(self):
        # localhost:cloths/<int:pk>/
       id=self.kwargs.get("pk")
       cloth_varient_object=ClothVarients.objects.get(id=id)#clothvarientobject
       cloth_id=cloth_varient_object.cloth.id


       return reverse("cloth-detail",kwargs={"pk":cloth_id})

@signin_required
@is_admin
def offer_delete_view(request,*args,**kwargs):
    id=kwargs.get("pk")
    offer_object=Offers.objects.get(id=id)
    cloth_id=offer_object.clothvarient.cloth.id
    offer_object.delete()
    return redirect("cloth-detail",pk=cloth_id)

@signin_required
def sign_out_view(request,*args,**kwargs):
    logout(request)
    return redirect("signin")



   
   

youstaproject/yousta/templates/yousta/category_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>

{%if messages%}
    {%for m in messages%}

      <div>
        {{m}}
      </div>
    {%endfor%}

{%endif%}

    
<div class="container d-flex flex-column align-items-center mt-5">
   <div class="border border-4 p-5">
    <h1 class="text-center mb-3">Categories</h1>
    <div class="w-100">
     <form action="" method="post">
 
         {%csrf_token%}
         {{form.as_p}}
         <input type="submit" value="add">
     </form>
 
    </div>
 
    <div class="mt-5 w-100">
     <table class="table table-striped">
         <tr>
             <td>Name</td>
             <td>Action</td>
         </tr>
         {%for cat in categories%}
            <tr>
             <td>{{cat.name}}</td>
             <td>
                 <a href="{%url 'remove-category' cat.id%}">delete</a>
             </td>
     
            </tr>
         {%endfor%}
     
     </table>
    </div>
 
   </div>


   


</div>

</body>
</html>

youstaproject/yousta/templates/yousta/cloth_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body style="height:100vh;">

{%if messages%}
    {%for m in messages%}

      <div>
        {{m}}
      </div>
    {%endfor%}

{%endif%}

    
<div class="container d-flex align-items-center justify-content-center">
    <form action="" method="post" enctype="multipart/form-data" class="border border-2 shadow p-5">

        {%csrf_token%}
        {{form.as_p}}
        <input type="submit" value="add">
    </form>


</div>

</body>
</html>

youstaproject/yousta/templates/yousta/cloth_detail.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>

</head>

<body style="height: 100vh;">

  <div class="container">

    <div class="row">

      <div class="col-4">
        <div class="card" style="width:100%">
          <img src="{{cloth.image.url}}" class="card-img-top" alt="..." height="200px">
          <div class="card-body">
            <h5 class="card-title">{{cloth.name}}</h5>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">{{cloth.material}}</li>
            <li class="list-group-item">{{cloth.brand}}</li>
            <li class="list-group-item">{{cloth.category}}</li>
          </ul>
          <div class="card-body">
            <a href="#" class="card-link">Card link</a>
            <a href="#" class="card-link">Another link</a>
          </div>
        </div>
      </div>
      <div class="col-8 border boredr-dark">
        <table class="table table-striped">
          <tr>

            <td>Price</td>
            <td>Size</td>
            <td>color</td>
            <td>offers</td>
            <td>Action</td>
          </tr>
          {%for v in cloth.clothvarients_set.all%}

          <tr>
            <td>{{v.price}}</td>
            <td>{{v.size}}</td>
            <td>{{v.color}}</td>
            <td>
              <div class="accordion" id="accordionExample">
                <div class="accordion-item">
                  <h2 class="accordion-header">
                    <button class="accordion-button" type="button" data-bs-toggle="collapse"
                      data-bs-target="#collapseOne{{forloop.counter}}" aria-expanded="true" aria-controls="collapseOne">
                      offers
                    </button>
                  </h2>
                  <div id="collapseOne{{forloop.counter}}" class="accordion-collapse collapse show"
                    data-bs-parent="#accordionExample">
                    <div class="accordion-body">


                      {%for o in v.offers_set.all%}

                      <div class="border border-top-0 border-start-0 border-end-0 border-bottom-1">
                        price:{{o.price}} start_date:{{o.start_date|date:"SHORT_DATE_FORMAT"}} |due_date :{{o.due_date|date:"SHORT_DATE_FORMAT"}}


                      </div>
                      {%endfor%}

                    </div>
                  </div>
                </div>
              </div>
      </div>
      </td>

      <td>
        <a href="{%url 'update-varient' v.id %}" class="btn btn-outline-info">Edit</a>
        <a href="{%url 'remove-varient' v.id%}" class="btn btn-outline-danger">remove</a>

        <a href="{%url 'offers-add' v.id%}" class="btn btn-outline-success">add offer</a>
      </td>
      </tr>
      {%endfor%}

      </table>
    </div>





  </div>

  <div class="row">
    {%for v in cloth.clothvarients_set.all%}
    {%for o in v.offers_set.all%}
    <div class="border p-3">

      <div>
        size {{o.clothvarient.size}} | color {{o.clothvarient.color}}
      </div>

      <div><span>offer price$ {{o.price}}</span></div>
      <div>start_date : {{o.start_date}}</div>
      <div>due_date :{{o.due_date}}</div>
      <a href="{%url 'delete-offer' o.id%}">delete</a>
    </div>
    {%endfor%}

    {%endfor%}

  </div>



  </div>



</body>

</html>

youstaproject/yousta/templates/yousta/cloth_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body style="height:100vh;">

{%if messages%}
    {%for m in messages%}

      <div>
        {{m}}
      </div>
    {%endfor%}

{%endif%}

    
<div class="container d-flex align-items-center justify-content-center">
    <form action="" method="post" enctype="multipart/form-data" class="border border-2 shadow p-5">

        {%csrf_token%}
        {{form.as_p}}
        <input type="submit" value="change">
    </form>


</div>

</body>
</html>

youstaproject/yousta/templates/yousta/cloth_list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>

<body>

    <div class="container">

        <table class="table table-striped">

            <tr>
                <td>Name</td>
                <td>Material</td>
                <td>Brand</td>
                <td>image</td>
            </tr>

            {%for ct in cloths%}
            <tr>
                <td>{{ct.name}}</td>
                <td>{{ct.material}}</td>
                <td>{{ct.brand}}</td>
                <td>
                    <img src="{{ct.image.url}}" alt="" width="100px" height="200px" style="object-fit: contain;">
                </td>

                <td>
                    <a href="{%url 'cloth-remove' ct.id%}">delete</a>
                    
                    <a href="{%url 'add-varient' ct.id%}">add clothvarient</a>
                    <a href="{%url 'cloth-detail' ct.id%}">view</a>
                </td>
            </tr>
            {%endfor%}

        </table>




    </div>


</body>

</html>

youstaproject/yousta/templates/yousta/clothvarient_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body style="height:100vh;">

{%if messages%}
    {%for m in messages%}

      <div>
        {{m}}
      </div>
    {%endfor%}

{%endif%}

    
<div class="container d-flex align-items-center justify-content-center">
    <form action="" method="post" enctype="multipart/form-data" class="border border-2 shadow p-5">

        {%csrf_token%}
        {{form.as_p}}
        <input type="submit" value="add">
    </form>


</div>

</body>
</html>

youstaproject/yousta/templates/yousta/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
    <style>
        body {
            height: 100vh;
            background-color: #4158D0;
            background-image: linear-gradient(43deg, #4158D0 0%, #C850C0 46%, #FFCC70 100%);

        }

        .section {
            width: 40%;
            height: 80%;

        }



        .btn-grad {
            background-image: linear-gradient(to right, #4776E6 0%, #8E54E9 51%, #4776E6 100%);
            margin: 10px;
            padding: 10px 45px;
            text-align: center;
            text-transform: uppercase;
            transition: 0.5s;
            background-size: 200% auto;
            color: white;
            box-shadow: 0 0 20px #eee;
            border-radius: 10px;
            display: block;
        }

        .btn-grad:hover {
            background-position: right center;
            /* change the direction of the change here */
            color: #fff;
            text-decoration: none;
        }
    </style>
</head>

<body>

    {%if messages%}

    {%for m in messages%}

    {%if m.level == DEFAULT_MESSAGE_LEVELS.ERROR %}

    <div class="d-flex justify-content-center mb-2">
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <strong>Holy guacamole!</strong> {{m}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    </div>

    {%endif%}


    {%endfor%}



    {%endif%}

    <div class="container h-100 d-flex justify-content-center align-items-center">



        <div class="section rounded-3 bg-white p-5 shadow">
            <div class="text-center mb-5">
                <h1 class="fw-bolder">Login</h1>
            </div>
            <form action="" method="post">
                {%csrf_token%}
                <div class="mb-4">
                    <label for="" class="form-label">username</label>
                    <input type="text" placeholder="Type your username"
                        class="form-control border border-start-0 border-top-0 border-end-0" name="username">
                </div>
                <div class="mb-4">
                    <label for="" class="form-label">password</label>
                    <input type="text" placeholder="Type your password"
                        class="form-control border border-start-0 border-top-0 border-end-0" name="password">
                </div>
                <div>
                    <button class="form-control btn-grad rounded-pill" type="submit">Login</button>
                </div>

                <div class="social-auth d-flex flex-column align-items-center">

                    <div>
                        <label for="">or SignUpusging</label>

                    </div>

                    <div>
                        <a href="">fb</a>
                        <a href="">twitter</a>
                        <a href="">google</a>
                    </div>


                </div>


            </form>


        </div>

    </div>


</body>

</html>

youstaproject/yousta/templates/yousta/loginold.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

{%if messages%}
    {%for m in messages%}

      <div>
        {{m}}
      </div>
    {%endfor%}

{%endif%}

    
<div class="container">
<form action="" method="post">

    {%csrf_token%}
    {{form.as_p}}
    <input type="submit" value="login">
</form>

</div>

</body>
</html>